api:
  insecure: true
  dashboard: true
entryPoints:
  web:
    address: :3000
  websecure:
    address: ':443'
    http:
      tls:
        certResolver: myresolver
certificatesResolvers:
  myresolver:
    acme:
      email: your-email@example.com
      storage: acme.json
      httpChallenge:
        entryPoint: web
accessLog: {}
#log:
#  filePath: "/var/log/traefik.log"
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    httpClientTimeout: 300
